spring.application.name=appVentasDipBKSpring

# CONFIGURACIONES PRINCIPALES
# QUITAR EL BANNER
spring.main.banner-mode=off

# THYMELEAF
spring.thymeleaf.check-template-location=true

# CONEXION BD
spring.datasource.url=jdbc:mysql://localhost:3306/ejemplosjdbc?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=rootAdmin2022#

# CONFIGURACION LOGGIN
logging.level.root=WARN
logging.level.org.springframework.boot=INFO
logging.level.mx.com.mxds=INFO
logging.level.org.springframework.boot.tomcat=INFO

# CONFIGURACION SERVER
# PUERTO DE ARRANQUE
server.port=8082
# CONTEXTO DE LA APLICACION
server.servlet.context-path=/AppVtas

# PARA EXPLORAR DEL ARRANQUE DE SPRING BOOT
#debug=true
